import assert from 'node:assert/strict';
import { access, mkdir, readFile, rename, rm, symlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {
  canonicalJson,
  listFiles,
  loadRuntime,
  makeConsumerWorkspace,
  sha256,
  snapshotFiles,
} from './helpers.mjs';

const MARKER = 'GENERATED by cms-field-vocabulary; DO NOT EDIT';

async function rewriteConfig(workspace, updates) {
  Object.assign(workspace.config, updates);
  await writeFile(path.join(workspace.root, workspace.configPath), canonicalJson(workspace.config));
}

test('projection bytes are deterministic across roots and an unchanged re-sync is a no-op', async (t) => {
  const first = await makeConsumerWorkspace({ profile: 'generic' });
  const second = await makeConsumerWorkspace({ profile: 'generic' });
  t.after(() => Promise.all([first.cleanup(), second.cleanup()]));
  const { checkProjection, syncProjection } = await loadRuntime();
  assert.equal(await syncProjection({ configPath: first.configPath, root: first.root }), 'synced');
  assert.equal(await syncProjection({ configPath: second.configPath, root: second.root }), 'synced');
  assert.deepEqual(await snapshotFiles(first.target), await snapshotFiles(second.target));
  const before = await snapshotFiles(first.target);
  assert.equal(await syncProjection({ configPath: first.configPath, root: first.root, ifNeeded: true }), 'current');
  assert.deepEqual(await snapshotFiles(first.target), before);
  await checkProjection({ configPath: first.configPath, root: first.root });
});

test('projection contains only routed adapter shards and strips official evidence from agent context', async (t) => {
  const workspace = await makeConsumerWorkspace({ profile: 'generic' });
  t.after(() => workspace.cleanup());
  const { syncProjection } = await loadRuntime();
  await syncProjection({ configPath: workspace.configPath, root: workspace.root });
  const adapters = JSON.parse(await readFile(path.join(workspace.target, 'adapters.json'), 'utf8'));
  const contractFiles = (await listFiles(path.join(workspace.target, 'contracts'))).map((file) => file.replace(/\.json$/, ''));
  assert.deepEqual(contractFiles, Object.keys(adapters.adapters).sort());
  for (const adapter of contractFiles) {
    const contract = await readFile(path.join(workspace.target, 'contracts', `${adapter}.json`), 'utf8');
    assert.doesNotMatch(contract, /"evidence"|"claimRefs"|"typicalUse"|"editorBehavior"|"storageShape"|"deliveryShape"/);
    assert.doesNotMatch(contract, /https?:\/\//);
  }
  assert.equal(contractFiles.includes('wordpress.core71-rest-schema'), false);
  assert.equal(contractFiles.includes('optimizely-saas.cms-api-v1'), false);
});

test('projection marker and manifest bind exact package, profile, config, catalog, bytes, and digests', async (t) => {
  const workspace = await makeConsumerWorkspace({ profile: 'ai-orchestration' });
  t.after(() => workspace.cleanup());
  const { syncProjection } = await loadRuntime();
  await syncProjection({ configPath: workspace.configPath, root: workspace.root });
  const marker = await readFile(path.join(workspace.target, '.cms-field-vocabulary-generated'), 'utf8');
  const manifest = JSON.parse(await readFile(path.join(workspace.target, 'projection-manifest.json'), 'utf8'));
  const source = JSON.parse(await readFile(path.join(workspace.target, 'source.json'), 'utf8'));
  assert.equal(marker.split('\n')[0], MARKER);
  assert.match(marker, /^GENERATED by cms-field-vocabulary; DO NOT EDIT\npackage=.+\nprofile=ai-orchestration\ncatalog=sha256:[a-f0-9]{64}\n$/);
  assert.equal(manifest.profile, 'ai-orchestration');
  assert.equal(manifest.adapter, 'contentful');
  assert.equal(manifest.vocabularyProfile, 'contentful.cma.saas');
  assert.equal(manifest.generatedBy, 'cms-field-vocabulary');
  assert.equal(manifest.configDigest, `sha256:${sha256(canonicalJson(workspace.config))}`);
  assert.equal(manifest.catalogDigest, source.catalogDigest);
  assert.match(source.sourceLockDigest, /^sha256:[a-f0-9]{64}$/);
  assert.equal(source.includeProvenanceInAgentContext, false);
  assert.equal(source.activeAdapter, 'contentful');
  assert.equal(source.activeProfile, 'contentful.cma.saas');
  assert.deepEqual(manifest.files.map((file) => file.path), [...manifest.files.map((file) => file.path)].sort());
  assert.equal(manifest.files.some((file) => file.path === 'projection-manifest.json'), false);
  for (const file of manifest.files) {
    const contents = await readFile(path.join(workspace.target, file.path));
    assert.equal(file.bytes, contents.byteLength, file.path);
    assert.equal(file.sha256, sha256(contents), file.path);
  }
});

test('unmarked, modified, and unexpected projection content is never overwritten', async (t) => {
  const { checkProjection, syncProjection } = await loadRuntime();

  const unmarked = await makeConsumerWorkspace();
  t.after(() => unmarked.cleanup());
  await mkdir(unmarked.target, { recursive: true });
  await writeFile(path.join(unmarked.target, 'owned.txt'), 'consumer data\n');
  await assert.rejects(
    syncProjection({ configPath: unmarked.configPath, root: unmarked.root }),
    /Refusing to overwrite unmarked target/,
  );
  assert.equal(await readFile(path.join(unmarked.target, 'owned.txt'), 'utf8'), 'consumer data\n');

  const modified = await makeConsumerWorkspace();
  t.after(() => modified.cleanup());
  await syncProjection({ configPath: modified.configPath, root: modified.root });
  await writeFile(path.join(modified.target, 'adapters.json'), '{"edited":true}\n');
  await assert.rejects(
    checkProjection({ configPath: modified.configPath, root: modified.root }),
    /modified adapters\.json/,
  );
  await assert.rejects(
    syncProjection({ configPath: modified.configPath, root: modified.root }),
    /modified adapters\.json/,
  );

  const unexpected = await makeConsumerWorkspace();
  t.after(() => unexpected.cleanup());
  await syncProjection({ configPath: unexpected.configPath, root: unexpected.root });
  await writeFile(path.join(unexpected.target, 'consumer-note.txt'), 'do not remove\n');
  await assert.rejects(
    syncProjection({ configPath: unexpected.configPath, root: unexpected.root }),
    /unexpected consumer-note\.txt/,
  );
  assert.equal(await readFile(path.join(unexpected.target, 'consumer-note.txt'), 'utf8'), 'do not remove\n');
});

test('rewriting a digest cannot hide a modified generated file from exact projection checking', async (t) => {
  const workspace = await makeConsumerWorkspace();
  t.after(() => workspace.cleanup());
  const { checkProjection, syncProjection } = await loadRuntime();
  await syncProjection({ configPath: workspace.configPath, root: workspace.root });
  const adaptersPath = path.join(workspace.target, 'adapters.json');
  const manifestPath = path.join(workspace.target, 'projection-manifest.json');
  const changed = '{"schemaVersion":1,"adapters":{}}\n';
  await writeFile(adaptersPath, changed);
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  const entry = manifest.files.find((file) => file.path === 'adapters.json');
  entry.sha256 = sha256(changed);
  entry.bytes = Buffer.byteLength(changed);
  await writeFile(manifestPath, canonicalJson(manifest));
  await assert.rejects(
    checkProjection({ configPath: workspace.configPath, root: workspace.root }),
    /adapters\.json differs|projection-manifest\.json differs/,
  );
  assert.equal(await syncProjection({ configPath: workspace.configPath, root: workspace.root }), 'synced');
  await checkProjection({ configPath: workspace.configPath, root: workspace.root });
});

test('a clean projection can migrate atomically when the configured consumer profile changes', async (t) => {
  const workspace = await makeConsumerWorkspace({ profile: 'generic' });
  t.after(() => workspace.cleanup());
  const { checkProjection, syncProjection } = await loadRuntime();
  await syncProjection({ configPath: workspace.configPath, root: workspace.root });
  await rewriteConfig(workspace, { profile: 'cos' });
  assert.equal(await syncProjection({ configPath: workspace.configPath, root: workspace.root }), 'synced');
  await checkProjection({ configPath: workspace.configPath, root: workspace.root });
  const manifest = JSON.parse(await readFile(path.join(workspace.target, 'projection-manifest.json'), 'utf8'));
  const adapters = JSON.parse(await readFile(path.join(workspace.target, 'adapters.json'), 'utf8'));
  assert.equal(manifest.profile, 'cos');
  assert.equal(manifest.projectionMode, 'official-data');
  assert.deepEqual(Object.keys(adapters.adapters).sort(), [
    'contentful', 'contentstack', 'optimizely', 'optimizelypaas', 'sitecore',
    'sitecoreonprem', 'wordpress',
  ]);
});

test('COS projection contains only compact official field data and no agent rendering policy', async (t) => {
  const workspace = await makeConsumerWorkspace({ profile: 'cos' });
  t.after(() => workspace.cleanup());
  const { syncProjection } = await loadRuntime();
  await syncProjection({ configPath: workspace.configPath, root: workspace.root });
  const source = JSON.parse(await readFile(path.join(workspace.target, 'source.json'), 'utf8'));
  assert.equal(source.projectionMode, 'official-data');
  for (const file of await listFiles(path.join(workspace.target, 'contracts'))) {
    const projection = JSON.parse(await readFile(path.join(workspace.target, 'contracts', file), 'utf8'));
    assert.deepEqual(Object.keys(projection).sort(), [
      'adapter',
      'extensibility',
      'fields',
      'platform',
      'product',
      'profileId',
      'schemaVersion',
      'surface',
      'transport',
      'version',
    ]);
    assert.ok(projection.fields.length > 0, file);
    for (const field of projection.fields) {
      assert.deepEqual(
        Object.keys(field).filter((key) => !['canonicalId', 'nativeToken', 'displayName', 'valueShape', 'formats'].includes(key)),
        [],
        `${file}:${field.canonicalId}`,
      );
    }
    assert.doesNotMatch(
      JSON.stringify(projection),
      /"(?:agentProfile|rendererBindings|operations|renderingOperations|policyId|claims|evidence|typicalUse|editorBehavior|storageShape|deliveryShape)"/,
      file,
    );
  }
});

test('sync and check accept an absolute config path inside the consumer root and reject one outside it', async (t) => {
  const workspace = await makeConsumerWorkspace();
  const outsideConfig = `${workspace.root}-outside-config.json`;
  t.after(async () => {
    await workspace.cleanup();
    await rm(outsideConfig, { force: true });
  });
  const { checkProjection, syncProjection } = await loadRuntime();
  const absoluteConfig = path.join(workspace.root, workspace.configPath);
  assert.equal(await syncProjection({ configPath: absoluteConfig, root: workspace.root }), 'synced');
  await checkProjection({ configPath: absoluteConfig, root: workspace.root });
  await writeFile(outsideConfig, canonicalJson(workspace.config));
  await assert.rejects(
    syncProjection({ configPath: outsideConfig, root: workspace.root }),
    /Consumer config escapes the consumer root/,
  );
});

test('projection target rejects traversal and absolute paths before writing', async (t) => {
  const traversal = await makeConsumerWorkspace();
  const absolute = await makeConsumerWorkspace();
  t.after(() => Promise.all([traversal.cleanup(), absolute.cleanup()]));
  const { syncProjection } = await loadRuntime();

  const escapedName = `${path.basename(traversal.root)}-escape`;
  await rewriteConfig(traversal, { target: `../${escapedName}` });
  await assert.rejects(
    syncProjection({ configPath: traversal.configPath, root: traversal.root }),
    /Projection target escapes the consumer root/,
  );
  await assert.rejects(access(path.resolve(traversal.root, '..', escapedName)));

  await rewriteConfig(absolute, { target: path.join(absolute.root, 'absolute-target') });
  await assert.rejects(
    syncProjection({ configPath: absolute.configPath, root: absolute.root }),
    /Projection target must be relative/,
  );
  await assert.rejects(access(path.join(absolute.root, 'absolute-target')));

  const rootTarget = await makeConsumerWorkspace();
  t.after(() => rootTarget.cleanup());
  await rewriteConfig(rootTarget, { target: '.' });
  await assert.rejects(
    syncProjection({ configPath: rootTarget.configPath, root: rootTarget.root }),
    /Projection target cannot be the consumer root/,
  );
});

test('consumer adapters must be own routing-map properties', async (t) => {
  const { syncProjection } = await loadRuntime();
  for (const adapter of ['toString', 'constructor', '__proto__']) {
    const workspace = await makeConsumerWorkspace();
    t.after(() => workspace.cleanup());
    await rewriteConfig(workspace, { adapter });
    await assert.rejects(
      syncProjection({ configPath: workspace.configPath, root: workspace.root }),
      new RegExp(`Unknown adapter ${adapter}`),
    );
    await assert.rejects(access(workspace.target));
  }
});

test('sync and check reject any symlink component in the projection target', async (t) => {
  const workspace = await makeConsumerWorkspace({ target: 'linked/projection' });
  t.after(() => workspace.cleanup());
  const { checkProjection, syncProjection } = await loadRuntime();
  await mkdir(path.join(workspace.root, 'real'), { recursive: true });
  await symlink('real', path.join(workspace.root, 'linked'));
  await assert.rejects(
    syncProjection({ configPath: workspace.configPath, root: workspace.root }),
    /Projection path cannot traverse a symlink/,
  );
  await assert.rejects(
    checkProjection({ configPath: workspace.configPath, root: workspace.root }),
    /Projection path cannot traverse a symlink/,
  );
});

test('sync and check reject symlinked files inside an otherwise valid projection', async (t) => {
  const workspace = await makeConsumerWorkspace();
  t.after(() => workspace.cleanup());
  const { checkProjection, syncProjection } = await loadRuntime();
  await syncProjection({ configPath: workspace.configPath, root: workspace.root });
  const adaptersPath = path.join(workspace.target, 'adapters.json');
  const externalPath = path.join(path.dirname(workspace.target), 'external-adapters.json');
  await writeFile(externalPath, await readFile(adaptersPath));
  await rm(adaptersPath);
  await symlink('../external-adapters.json', adaptersPath);
  await assert.rejects(
    checkProjection({ configPath: workspace.configPath, root: workspace.root }),
    /Projection path cannot traverse a symlink/,
  );
  await assert.rejects(
    syncProjection({ configPath: workspace.configPath, root: workspace.root }),
    /Projection path cannot traverse a symlink/,
  );
});

test('resolved-contract output rejects traversal, absolute paths, and symlink components', async (t) => {
  const workspace = await makeConsumerWorkspace();
  t.after(() => workspace.cleanup());
  const { resolveProjectionFields, syncProjection } = await loadRuntime();
  await syncProjection({ configPath: workspace.configPath, root: workspace.root });
  const base = {
    configPath: workspace.configPath,
    fieldIds: ['contentful.cma.saas.Symbol'],
    root: workspace.root,
  };
  await assert.rejects(
    resolveProjectionFields({ ...base, output: '../escape.json' }),
    /Resolved contract output escapes the consumer root/,
  );
  await assert.rejects(
    resolveProjectionFields({ ...base, output: path.join(workspace.root, 'absolute.json') }),
    /Resolved contract output must be relative/,
  );
  await assert.rejects(
    resolveProjectionFields({ ...base, output: '.' }),
    /Resolved contract output cannot be the consumer root/,
  );
  await mkdir(path.join(workspace.root, 'real-output'), { recursive: true });
  await symlink('real-output', path.join(workspace.root, 'linked-output'));
  await assert.rejects(
    resolveProjectionFields({ ...base, output: 'linked-output/result.json' }),
    /Projection path cannot traverse a symlink/,
  );
  await assert.rejects(access(path.join(workspace.root, 'real-output/result.json')));
});

test('failed resolved-contract promotion removes its private staging directory', async (t) => {
  const workspace = await makeConsumerWorkspace();
  t.after(() => workspace.cleanup());
  const { resolveProjectionFields, syncProjection } = await loadRuntime();
  await syncProjection({ configPath: workspace.configPath, root: workspace.root });
  const outputDirectory = path.join(workspace.root, 'resolved-target');
  await mkdir(outputDirectory);
  await assert.rejects(resolveProjectionFields({
    configPath: workspace.configPath,
    fieldIds: ['contentful.cma.saas.Symbol'],
    output: 'resolved-target',
    root: workspace.root,
  }));
  assert.deepEqual((await listFiles(workspace.root)).filter((file) => file.includes('.resolved-target.stage-')), []);
});

test('validateProjection rejects a target reached through a symlink', async (t) => {
  const workspace = await makeConsumerWorkspace({ target: 'linked-projection' });
  t.after(() => workspace.cleanup());
  const { syncProjection, validateProjection } = await loadRuntime();
  await syncProjection({ configPath: workspace.configPath, root: workspace.root });
  await rename(workspace.target, path.join(workspace.root, 'real-projection'));
  await symlink('real-projection', workspace.target);
  await assert.rejects(
    validateProjection(workspace.config, workspace.root),
    /Projection path cannot traverse a symlink/,
  );
});
