import { createHash } from 'node:crypto';
import { lstat, mkdir, mkdtemp, readFile, readdir, rename, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { canonicalCatalog, consumerProfiles, packageVersion } from './data.js';
import { getProfile, resolveFieldContracts, resolveOfficialDataProfile, resolveProfileContracts } from './catalog.js';
import type {
  ConsumerConfig,
  ProjectionManifest,
  RenderingSelectionInput,
  SelectedContract,
} from './types.js';

const GENERATED_MARKER = 'GENERATED by cms-field-vocabulary; DO NOT EDIT';

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, child]) => [key, canonicalize(child)]),
    );
  }
  return value;
}

function json(value: unknown): string {
  return `${JSON.stringify(canonicalize(value), null, 2)}\n`;
}

function sha256(value: string | Buffer): string {
  return createHash('sha256').update(value).digest('hex');
}

function validateConfigObject(config: unknown): asserts config is ConsumerConfig {
  if (!config || typeof config !== 'object' || Array.isArray(config)) throw new Error('Consumer config must be an object');
  const value = config as Record<string, unknown>;
  const allowed = new Set(['$schema', 'packageName', 'profile', 'adapter', 'target']);
  for (const key of Object.keys(value)) if (!allowed.has(key)) throw new Error(`Consumer config contains unknown property: ${key}`);
  if (typeof value.$schema !== 'string' || value.$schema.length === 0) throw new Error('Consumer config requires $schema');
  if (value.packageName !== 'cms-field-vocabulary') throw new Error('Consumer config packageName must be cms-field-vocabulary');
  if (!['ai-orchestration', 'cos', 'generic'].includes(String(value.profile))) throw new Error(`Unknown consumer profile: ${String(value.profile)}`);
  if (typeof value.adapter !== 'string' || value.adapter.length === 0) throw new Error('Consumer config requires adapter');
  const consumer = consumerProfiles.get(value.profile as string);
  if (!consumer || !Object.hasOwn(consumer.adapters, value.adapter)) {
    throw new Error(`Unknown adapter ${value.adapter} for consumer profile ${String(value.profile)}`);
  }
  if (typeof value.target !== 'string' || value.target.length === 0) throw new Error('Consumer config requires target');
}

async function readConfig(configPath: string): Promise<ConsumerConfig> {
  const parsed: unknown = JSON.parse(await readFile(configPath, 'utf8'));
  validateConfigObject(parsed);
  return parsed;
}

async function assertNoSymlinkComponents(root: string, target: string): Promise<void> {
  const relative = path.relative(root, target);
  let current = root;
  for (const segment of relative.split(path.sep).filter(Boolean)) {
    current = path.join(current, segment);
    try {
      const info = await lstat(current);
      if (info.isSymbolicLink()) throw new Error(`Projection path cannot traverse a symlink: ${current}`);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
      throw error;
    }
  }
}

function resolveSafePath(root: string, relativePath: string, label: string): string {
  if (path.isAbsolute(relativePath)) throw new Error(`${label} must be relative`);
  const resolved = path.resolve(root, relativePath);
  if (resolved === root) throw new Error(`${label} cannot be the consumer root`);
  if (!resolved.startsWith(`${root}${path.sep}`)) throw new Error(`${label} escapes the consumer root`);
  return resolved;
}

function resolveConfigPath(root: string, configPath: string): string {
  const resolved = path.resolve(root, configPath);
  if (resolved !== root && !resolved.startsWith(`${root}${path.sep}`)) {
    throw new Error('Consumer config escapes the consumer root');
  }
  return resolved;
}

function buildProjection(config: ConsumerConfig): Map<string, string> {
  const consumer = consumerProfiles.get(config.profile);
  if (!consumer) throw new Error(`Unknown consumer profile: ${config.profile}`);
  if (!Object.hasOwn(consumer.adapters, config.adapter)) {
    throw new Error(`Unknown adapter ${config.adapter} for consumer profile ${consumer.id}`);
  }
  const activeProfile = consumer.adapters[config.adapter];
  if (!activeProfile) throw new Error(`Adapter ${config.adapter} has no vocabulary profile for consumer ${consumer.id}`);
  const catalogDigest = `sha256:${sha256(json(canonicalCatalog))}`;
  const configDigest = `sha256:${sha256(json(config))}`;
  const files = new Map<string, string>();
  files.set('.cms-field-vocabulary-generated', `${GENERATED_MARKER}\npackage=${packageVersion}\nprofile=${consumer.id}\ncatalog=${catalogDigest}\n`);
  files.set('source.json', json({
    generatedBy: 'cms-field-vocabulary',
    packageVersion,
    schemaVersion: 1,
    catalogDigest,
    sourceLockDigest: canonicalCatalog.sourceLockDigest,
    consumerProfile: consumer.id,
    projectionMode: consumer.outputMode,
    activeAdapter: config.adapter,
    activeProfile,
    includeProvenanceInAgentContext: false,
  }));
  files.set('adapters.json', json({ schemaVersion: 1, adapters: consumer.adapters }));
  for (const [adapter, profileId] of Object.entries(consumer.adapters).sort(([left], [right]) => left.localeCompare(right))) {
    if (consumer.outputMode === 'official-data') {
      files.set(`contracts/${adapter}.json`, json(resolveOfficialDataProfile(profileId, adapter)));
      continue;
    }
    if (!consumer.agentProfile) throw new Error(`Consumer profile ${consumer.id} requires an agent profile`);
    const fieldIds = getProfile(profileId).fields.map((field) => field.canonicalId);
    const selected = resolveProfileContracts({ profileId, fieldIds, agentProfile: consumer.agentProfile });
    files.set(`contracts/${adapter}.json`, json({ adapter, ...selected }));
  }
  const manifestFiles = [...files.entries()]
    .map(([filePath, content]) => ({ path: filePath, sha256: sha256(content), bytes: Buffer.byteLength(content) }))
    .sort((left, right) => left.path.localeCompare(right.path));
  const manifest: ProjectionManifest = {
    schemaVersion: 1,
    generatedBy: 'cms-field-vocabulary',
    packageVersion,
    profile: consumer.id,
    adapter: config.adapter,
    projectionMode: consumer.outputMode,
    vocabularyProfile: activeProfile,
    catalogDigest,
    configDigest,
    files: manifestFiles,
  };
  files.set('projection-manifest.json', json(manifest));
  return files;
}

async function listFiles(root: string): Promise<string[]> {
  const output: string[] = [];
  async function visit(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const absolute = path.join(directory, entry.name);
      if (entry.isSymbolicLink()) throw new Error(`Projection path cannot traverse a symlink: ${absolute}`);
      if (entry.isDirectory()) await visit(absolute);
      else output.push(path.relative(root, absolute).split(path.sep).join('/'));
    }
  }
  await visit(root);
  return output.sort();
}

async function compareProjection(target: string, expected: Map<string, string>): Promise<string[]> {
  const errors: string[] = [];
  let actualFiles: string[];
  try {
    actualFiles = await listFiles(target);
  } catch {
    return [`Projection target is missing: ${target}`];
  }
  const expectedFiles = [...expected.keys()].sort();
  for (const file of expectedFiles) {
    try {
      const actual = await readFile(path.join(target, file), 'utf8');
      if (actual !== expected.get(file)) errors.push(`${file} differs from the exact installed projection`);
    } catch {
      errors.push(`${file} is missing`);
    }
  }
  for (const file of actualFiles) if (!expected.has(file)) errors.push(`${file} is unexpected`);
  return errors;
}

async function verifyExistingOwnership(target: string): Promise<void> {
  const marker = await readFile(path.join(target, '.cms-field-vocabulary-generated'), 'utf8').catch(() => '');
  if (!marker.startsWith(GENERATED_MARKER)) throw new Error(`Refusing to overwrite unmarked target: ${target}`);
  const manifest = JSON.parse(await readFile(path.join(target, 'projection-manifest.json'), 'utf8')) as ProjectionManifest;
  const expectedFiles = new Set([...manifest.files.map((file) => file.path), 'projection-manifest.json']);
  const actualFiles = await listFiles(target);
  for (const file of actualFiles) if (!expectedFiles.has(file)) throw new Error(`Refusing to overwrite dirty projection; unexpected ${file}`);
  for (const file of manifest.files) {
    const contents = await readFile(path.join(target, file.path));
    if (sha256(contents) !== file.sha256 || contents.byteLength !== file.bytes) throw new Error(`Refusing to overwrite dirty projection; modified ${file.path}`);
  }
}

async function writeProjection(root: string, files: Map<string, string>): Promise<void> {
  for (const [relative, content] of files) {
    const absolute = path.join(root, relative);
    await mkdir(path.dirname(absolute), { recursive: true });
    await writeFile(absolute, content);
  }
}

export async function syncProjection(options: { configPath: string; root?: string; ifNeeded?: boolean }): Promise<'synced' | 'current'> {
  const root = path.resolve(options.root || process.cwd());
  const configPath = resolveConfigPath(root, options.configPath);
  await assertNoSymlinkComponents(root, configPath);
  const config = await readConfig(configPath);
  const target = resolveSafePath(root, config.target, 'Projection target');
  await assertNoSymlinkComponents(root, target);
  const expected = buildProjection(config);
  let exists = false;
  try {
    exists = (await stat(target)).isDirectory();
  } catch {}
  if (exists) {
    await verifyExistingOwnership(target);
    const errors = await compareProjection(target, expected);
    if (errors.length === 0 && options.ifNeeded) return 'current';
  }
  await mkdir(path.dirname(target), { recursive: true });
  const stage = await mkdtemp(path.join(path.dirname(target), '.cms-field-vocabulary-stage-'));
  const backup = path.join(path.dirname(target), `.cms-field-vocabulary-backup-${process.pid}-${Date.now()}`);
  let backedUp = false;
  try {
    await writeProjection(stage, expected);
    if (exists) {
      await rename(target, backup);
      backedUp = true;
    }
    await rename(stage, target);
    if (backedUp) await rm(backup, { recursive: true, force: true });
    return 'synced';
  } catch (error) {
    await rm(stage, { recursive: true, force: true }).catch(() => undefined);
    if (backedUp) {
      await rm(target, { recursive: true, force: true }).catch(() => undefined);
      await rename(backup, target).catch(() => undefined);
    }
    throw error;
  }
}

export async function checkProjection(options: { configPath: string; root?: string }): Promise<void> {
  const root = path.resolve(options.root || process.cwd());
  const configPath = resolveConfigPath(root, options.configPath);
  await assertNoSymlinkComponents(root, configPath);
  const config = await readConfig(configPath);
  const target = resolveSafePath(root, config.target, 'Projection target');
  await assertNoSymlinkComponents(root, target);
  await verifyExistingOwnership(target);
  const errors = await compareProjection(target, buildProjection(config));
  if (errors.length > 0) throw new Error(errors.join('\n'));
}

export async function validateProjection(config: ConsumerConfig, root = process.cwd()): Promise<void> {
  validateConfigObject(config);
  const resolvedRoot = path.resolve(root);
  const target = resolveSafePath(resolvedRoot, config.target, 'Projection target');
  await assertNoSymlinkComponents(resolvedRoot, target);
  await verifyExistingOwnership(target);
  const errors = await compareProjection(target, buildProjection(config));
  if (errors.length > 0) throw new Error(errors.join('\n'));
}

export async function resolveProjectionFields(options: {
  configPath: string;
  fieldIds: string[];
  output: string;
  renderingSelections?: RenderingSelectionInput[];
  root?: string;
}): Promise<SelectedContract | null> {
  if (options.fieldIds.length === 0) {
    if ((options.renderingSelections?.length || 0) > 0) {
      throw new Error('Rendering selections require at least one requested field');
    }
    return null;
  }
  const root = path.resolve(options.root || process.cwd());
  const configPath = resolveConfigPath(root, options.configPath);
  await assertNoSymlinkComponents(root, configPath);
  const config = await readConfig(configPath);
  await checkProjection({ configPath: options.configPath, root });
  const consumer = consumerProfiles.get(config.profile);
  if (!consumer) throw new Error(`Unknown consumer profile: ${config.profile}`);
  const matchingProfiles = [...new Set(options.fieldIds.map((fieldId) => {
    const profile = canonicalCatalog.profiles.find((candidate) => candidate.fields.some((field) => field.canonicalId === fieldId));
    if (!profile) throw new Error(`Unknown CMS field ID: ${fieldId}`);
    return profile.id;
  }))];
  if (matchingProfiles.length !== 1) throw new Error('All selected field IDs must belong to one exact CMS profile');
  const profileId = matchingProfiles[0] as string;
  const activeProfile = consumer.adapters[config.adapter];
  if (profileId !== activeProfile) {
    throw new Error(`Profile ${profileId} is not active for adapter ${config.adapter}; expected ${activeProfile}`);
  }
  if (consumer.outputMode !== 'selected-contract' || !consumer.agentProfile) {
    throw new Error(`Consumer profile ${consumer.id} does not provide coding-agent contracts`);
  }
  const selected = resolveFieldContracts({
    profileId,
    fieldIds: options.fieldIds,
    agentProfile: consumer.agentProfile,
    ...(options.renderingSelections ? { renderingSelections: options.renderingSelections } : {}),
  });
  if (!selected) return null;
  const output = resolveSafePath(root, options.output, 'Resolved contract output');
  await assertNoSymlinkComponents(root, output);
  const outputDirectory = path.dirname(output);
  await mkdir(outputDirectory, { recursive: true });
  const stage = await mkdtemp(path.join(outputDirectory, `.${path.basename(output)}.stage-`));
  const stagedOutput = path.join(stage, path.basename(output));
  try {
    await writeFile(stagedOutput, json(selected), { flag: 'wx' });
    await rename(stagedOutput, output);
  } finally {
    await rm(stage, { recursive: true, force: true });
  }
  return selected;
}

export function temporaryProjectionRoot(): string {
  return path.join(os.tmpdir(), 'cms-field-vocabulary');
}
